import Head from "next/head";

// Data yang dilempar akan masuk ke props
export default function Layout(props) {
  return (
    <>
      <style jsx>
        {`
          background-color: #f1f1f1;
        `}
      </style>
      <div>
        {/* <Head> untuk menambahkan metadata pada halaman ini */}
        <Head>
          {/* Untuk menangkap title untuk tab */}
          <title>{props.title}</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        {props.children}
        {/* Untuk menangkap komponen pada index.js */}
      </div>
    </>
  );
}
